/* 골든 DSL 12종 — 손으로 쓴 정답. 모든 마일스톤의 회귀 테스트이자 few-shot 예시이자 공개 데모 샘플이다.
   단순 핀·스페이서에서 홈+나사+키홈 복합 축까지 난이도가 오른다. 값은 실제 규격(DIN 471/6885/332/76, ISO 261)을 따른다. */

export const GOLDENS = [
  {
    dsl: "vringon-shaft/1.0", id: "spacer", name: "Spacer sleeve", name_ko: "스페이서", part_class: "spacer", units: "mm", material: "A6061",
    drawing: { number: "VR-RB-001", scale: "2:1", projection: "third" },
    segments: [{ type: "cyl", length: 12, diameter: 24 }],
    transitions: [{ at: 0, type: "chamfer", size: 0.5 }, { at: 1, type: "chamfer", size: 0.5 }],
    grooves: [], bore: { through: true, segments: [{ length: 12, diameter: 16, tolerance: "H8" }], chamfer_left: 0.5, chamfer_right: 0.5 }, features: [],
    meta: { source: "golden", difficulty: 1 },
  },
  {
    dsl: "vringon-shaft/1.0", id: "clevis-pin", name: "Clevis pin", name_ko: "클레비스 핀", part_class: "pin", units: "mm", material: "S45C",
    drawing: { number: "VR-RB-002", scale: "2:1", projection: "third" },
    segments: [{ type: "cyl", length: 3, diameter: 16 }, { type: "cyl", length: 48, diameter: 12, tolerance: "h11" }],
    transitions: [{ at: 0, type: "chamfer", size: 0.5 }, { at: 2, type: "chamfer", size: 1 }],
    grooves: [], bore: null,
    features: [{ type: "cross_hole", position: 44, diameter: 3.2, through: true, angle: 0 }],
    meta: { source: "golden", difficulty: 1 },
  },
  {
    dsl: "vringon-shaft/1.0", id: "bushing", name: "Plain bushing", name_ko: "부시", part_class: "bushing", units: "mm", material: "C3604",
    drawing: { number: "VR-RB-003", scale: "2:1", projection: "third" },
    segments: [{ type: "cyl", length: 25, diameter: 30, tolerance: "m6" }],
    transitions: [{ at: 0, type: "chamfer", size: 0.5 }, { at: 1, type: "chamfer", size: 0.5 }],
    grooves: [], bore: { through: true, segments: [{ length: 25, diameter: 25, tolerance: "H7" }], chamfer_left: 0.5, chamfer_right: 0.5 },
    features: [{ type: "cross_hole", position: 12.5, diameter: 2.5, through: false, depth: 3.5, angle: 90 }],
    meta: { source: "golden", difficulty: 2 },
  },
  {
    dsl: "vringon-shaft/1.0", id: "flanged-bushing", name: "Flanged bushing", name_ko: "플랜지 부시", part_class: "bushing", units: "mm", material: "PBC2",
    drawing: { number: "VR-RB-004", scale: "2:1", projection: "third" },
    segments: [{ type: "cyl", length: 5, diameter: 40 }, { type: "cyl", length: 25, diameter: 30, tolerance: "n6" }],
    transitions: [{ at: 0, type: "chamfer", size: 0.5 }, { at: 1, type: "chamfer", size: 0.5 }, { at: 2, type: "chamfer", size: 0.5 }],
    grooves: [], bore: { through: true, segments: [{ length: 30, diameter: 22, tolerance: "H7" }], chamfer_left: 0.5, chamfer_right: 0.5 }, features: [],
    meta: { source: "golden", difficulty: 2 },
  },
  {
    dsl: "vringon-shaft/1.0", id: "roller", name: "Roller with stub axles", name_ko: "롤러", part_class: "roller", units: "mm", material: "SUS304",
    drawing: { number: "VR-RB-005", scale: "1:1", projection: "third" },
    segments: [
      { type: "cyl", length: 20, diameter: 20, tolerance: "h6", label: "베어링 자리" },
      { type: "cyl", length: 70, diameter: 45, roughness: "Ra 0.8" },
      { type: "cyl", length: 20, diameter: 20, tolerance: "h6", label: "베어링 자리" },
    ],
    transitions: [{ at: 0, type: "chamfer", size: 1.5 }, { at: 3, type: "chamfer", size: 1.5 }, { at: 1, type: "fillet", radius: 1.5 }, { at: 2, type: "fillet", radius: 1.5 }, { at: 1, type: "chamfer", size: 1 }, { at: 2, type: "chamfer", size: 1 }],
    grooves: [
      { segment: 0, offset: 6, width: 1.3, depth: 0.5, kind: "snap_ring", standard: "DIN 471 ⌀19×1.3" },
      { segment: 2, offset: 12.7, width: 1.3, depth: 0.5, kind: "snap_ring", standard: "DIN 471 ⌀19×1.3" },
    ],
    bore: null,
    features: [{ type: "center_hole", end: "left", form: "A", d: 2 }, { type: "center_hole", end: "right", form: "A", d: 2 }],
    meta: { source: "golden", difficulty: 3 },
  },
  {
    dsl: "vringon-shaft/1.0", id: "hex-stud", name: "Hex stepped stud", name_ko: "육각 단붙이 축", part_class: "shaft", units: "mm", material: "SUS303",
    drawing: { number: "VR-RB-006", scale: "2:1", projection: "third" },
    segments: [{ type: "cyl", length: 15, diameter: 20 }, { type: "cyl", length: 30, diameter: 12, tolerance: "h6" }, { type: "thread", length: 12, diameter: 10, spec: "M10", pitch: 1.5 }],
    transitions: [{ at: 0, type: "chamfer", size: 1 }, { at: 1, type: "fillet", radius: 1 }, { at: 3, type: "chamfer", size: 1.5 }],
    grooves: [], bore: null,
    features: [{ type: "hex", segment: 0, across_flats: 17 }, { type: "flat", segment: 1, offset: 5, length: 12, depth: 1.5, count: 1 }],
    meta: { source: "golden", difficulty: 3 },
  },
  {
    dsl: "vringon-shaft/1.0", id: "threaded-shaft", name: "Double-threaded shaft", name_ko: "양단 나사 축", part_class: "shaft", units: "mm", material: "S45C",
    drawing: { number: "VR-RB-007", scale: "1:1", projection: "third" },
    segments: [
      { type: "thread", length: 20, diameter: 12, spec: "M12", pitch: 1.75 },
      { type: "cyl", length: 60, diameter: 16, tolerance: "h7" },
      { type: "cyl", length: 20, diameter: 14 },
      { type: "thread", length: 18, diameter: 12, spec: "M12x1.25", pitch: 1.25 },
    ],
    transitions: [
      { at: 0, type: "chamfer", size: 1.5 }, { at: 4, type: "chamfer", size: 1.5 },
      { at: 1, type: "undercut", width: 5.25, depth: 1.3, standard: "DIN 76-A" }, { at: 3, type: "undercut", width: 3.75, depth: 0.94, standard: "DIN 76-A" },
      { at: 2, type: "fillet", radius: 0.5 },
    ],
    grooves: [], bore: null,
    features: [{ type: "cross_hole", position: 90, diameter: 3, through: true, angle: 0 }],
    meta: { source: "golden", difficulty: 3 },
  },
  {
    dsl: "vringon-shaft/1.0", id: "sleeve", name: "Stepped-bore sleeve", name_ko: "슬리브", part_class: "sleeve", units: "mm", material: "SUJ2",
    drawing: { number: "VR-RB-008", scale: "1:1", projection: "third" },
    segments: [{ type: "cyl", length: 60, diameter: 40, tolerance: "h6" }],
    transitions: [{ at: 0, type: "chamfer", size: 0.5 }, { at: 1, type: "chamfer", size: 0.5 }],
    grooves: [{ segment: 0, offset: 15, width: 2.4, depth: 1.9, kind: "o_ring", corner_radius: 0.2 }],
    bore: { through: true, segments: [{ length: 20, diameter: 30, tolerance: "H7" }, { length: 40, diameter: 28 }], chamfer_left: 0.5, chamfer_right: 0.5 },
    features: [],
    meta: { source: "golden", difficulty: 3 },
  },
  {
    dsl: "vringon-shaft/1.0", id: "taper-shaft", name: "Taper shaft with keyway", name_ko: "테이퍼 축", part_class: "shaft", units: "mm", material: "SCM440",
    drawing: { number: "VR-RB-009", scale: "1:1", projection: "third" },
    segments: [
      { type: "cyl", length: 35, diameter: 25, tolerance: "k6" },
      { type: "taper", length: 40, d_start: 25, d_end: 20 },
      { type: "thread", length: 20, diameter: 16, spec: "M16x1.5", pitch: 1.5 },
    ],
    transitions: [{ at: 0, type: "chamfer", size: 1 }, { at: 3, type: "chamfer", size: 1.5 }, { at: 2, type: "undercut", width: 4.5, depth: 1.1, standard: "DIN 76-A" }],
    grooves: [], bore: null,
    features: [
      { type: "keyway", segment: 0, offset: 8, length: 20, width: 8, depth: 4, kind: "parallel", standard: "DIN 6885 8×7" },
      { type: "center_hole", end: "left", form: "A", d: 2.5 },
    ],
    meta: { source: "golden", difficulty: 4 },
  },
  {
    dsl: "vringon-shaft/1.0", id: "motor-shaft", name: "Motor output shaft", name_ko: "모터 축", part_class: "shaft", units: "mm", material: "S45C",
    drawing: { number: "VR-RB-010", scale: "1:1", projection: "third" },
    segments: [
      { type: "cyl", length: 25, diameter: 15, tolerance: "j6", label: "베어링 자리" },
      { type: "cyl", length: 40, diameter: 17 },
      { type: "cyl", length: 60, diameter: 20, label: "로터 자리" },
      { type: "cyl", length: 40, diameter: 17 },
      { type: "cyl", length: 25, diameter: 15, tolerance: "j6", label: "베어링 자리" },
      { type: "cyl", length: 15, diameter: 12, tolerance: "h7", label: "출력 축" },
    ],
    transitions: [{ at: 0, type: "chamfer", size: 1 }, { at: 6, type: "chamfer", size: 1 }, { at: 1, type: "fillet", radius: 0.5 }, { at: 2, type: "fillet", radius: 1 }, { at: 3, type: "fillet", radius: 1 }, { at: 4, type: "fillet", radius: 0.5 }, { at: 5, type: "fillet", radius: 0.5 }],
    grooves: [{ segment: 4, offset: 4, width: 1.1, depth: 0.35, kind: "snap_ring", standard: "DIN 471 ⌀14.3×1.1" }],
    bore: null,
    features: [
      { type: "keyway", segment: 2, offset: 15, length: 30, width: 6, depth: 3.5, kind: "parallel", standard: "DIN 6885 6×6" },
      { type: "flat", segment: 5, offset: 2, length: 12, depth: 1.5, count: 1 },
      { type: "center_hole", end: "left", form: "A", d: 2 }, { type: "center_hole", end: "right", form: "A", d: 2 },
    ],
    meta: { source: "golden", difficulty: 4 },
  },
  {
    dsl: "vringon-shaft/1.0", id: "stepped-shaft", name: "Stepped shaft (showcase)", name_ko: "단붙이 축", part_class: "shaft", units: "mm", material: "S45C",
    drawing: { number: "VR-RB-011", scale: "1:1", projection: "third" },
    segments: [
      { type: "cyl", length: 30, diameter: 20, tolerance: "h6", label: "베어링 자리" },
      { type: "cyl", length: 40, diameter: 30, label: "기어 자리" },
      { type: "taper", length: 10, d_start: 30, d_end: 25 },
      { type: "thread", length: 20, diameter: 20, spec: "M20x1.5", pitch: 1.5 },
    ],
    transitions: [
      { at: 0, type: "chamfer", size: 1 }, { at: 1, type: "fillet", radius: 1.5 }, { at: 1, type: "chamfer", size: 1 },
      { at: 3, type: "undercut", width: 4.5, depth: 1.1, standard: "DIN 76-A" }, { at: 4, type: "chamfer", size: 1.5 },
    ],
    grooves: [{ segment: 1, offset: 10, width: 1.6, depth: 0.7, kind: "snap_ring", standard: "DIN 471 ⌀28.6×1.6" }],
    bore: null,
    features: [
      { type: "keyway", segment: 1, offset: 15, length: 20, width: 8, depth: 4, kind: "parallel", standard: "DIN 6885 8×7" },
      { type: "center_hole", end: "left", form: "A", d: 2.5 }, { type: "center_hole", end: "right", form: "A", d: 2 },
      { type: "cross_hole", position: 50, diameter: 4, through: true, angle: 0 },
    ],
    meta: { source: "golden", difficulty: 5 },
  },
  {
    dsl: "vringon-shaft/1.0", id: "spindle", name: "Small spindle", name_ko: "스핀들", part_class: "spindle", units: "mm", material: "SCM415",
    drawing: { number: "VR-RB-012", scale: "1:1", projection: "third" },
    segments: [
      { type: "thread", length: 14, diameter: 12, spec: "M12x1", pitch: 1 },
      { type: "cyl", length: 8, diameter: 14 },
      { type: "cyl", length: 20, diameter: 15, tolerance: "j5", label: "베어링 자리" },
      { type: "cyl", length: 45, diameter: 18 },
      { type: "cyl", length: 20, diameter: 15, tolerance: "j5", label: "베어링 자리" },
      { type: "cyl", length: 12, diameter: 14, tolerance: "h6" },
    ],
    transitions: [
      { at: 0, type: "chamfer", size: 1 }, { at: 6, type: "chamfer", size: 0.5 },
      { at: 1, type: "undercut", width: 3, depth: 0.75, standard: "DIN 76-A" },
      { at: 2, type: "fillet", radius: 0.5 }, { at: 3, type: "fillet", radius: 0.5 }, { at: 4, type: "fillet", radius: 0.5 }, { at: 5, type: "fillet", radius: 0.5 },
    ],
    grooves: [{ segment: 5, offset: 3, width: 1.1, depth: 0.35, kind: "snap_ring", standard: "DIN 471 ⌀13.4×1.1" }],
    bore: null,
    features: [
      { type: "keyway", segment: 3, offset: 12, length: 20, width: 6, depth: 3.5, kind: "parallel", standard: "DIN 6885 6×6" },
      { type: "center_hole", end: "right", form: "A", d: 2 },
    ],
    meta: { source: "golden", difficulty: 5 },
  },
  /* ---- 나사류 (볼트·스크루·스터드): ISO 4014/4762/4026/10642/DIN 938 근사 치수 ---- */
  {
    dsl: "vringon-shaft/1.0", id: "hex-bolt-m10", name: "Hex bolt M10x40", name_ko: "육각 볼트 M10×40", part_class: "other", units: "mm", material: "SCM435",
    drawing: { number: "VR-RB-013", scale: "2:1", projection: "third" },
    segments: [{ type: "cyl", length: 6.4, diameter: 18.48, label: "육각 머리" }, { type: "cyl", length: 14, diameter: 10 }, { type: "thread", length: 26, diameter: 10, spec: "M10", pitch: 1.5 }],
    transitions: [{ at: 0, type: "chamfer", size: 1, angle: 30 }, { at: 1, type: "fillet", radius: 0.6 }, { at: 3, type: "chamfer", size: 1.5 }],
    grooves: [], bore: null,
    features: [{ type: "hex", segment: 0, across_flats: 16 }],
    meta: { source: "golden", difficulty: 3 },
  },
  {
    dsl: "vringon-shaft/1.0", id: "socket-cap-m8", name: "Socket head cap screw M8x30", name_ko: "육각구멍붙이 볼트 M8×30", part_class: "other", units: "mm", material: "SCM435",
    drawing: { number: "VR-RB-014", scale: "2:1", projection: "third" },
    segments: [{ type: "cyl", length: 8, diameter: 13, label: "원통 머리" }, { type: "cyl", length: 8, diameter: 8 }, { type: "thread", length: 22, diameter: 8, spec: "M8", pitch: 1.25 }],
    transitions: [{ at: 0, type: "chamfer", size: 0.5 }, { at: 1, type: "fillet", radius: 0.5 }, { at: 3, type: "chamfer", size: 1 }],
    grooves: [], bore: null,
    features: [{ type: "hex_socket", end: "left", across_flats: 6, depth: 4 }],
    meta: { source: "golden", difficulty: 3 },
  },
  {
    dsl: "vringon-shaft/1.0", id: "set-screw-m6", name: "Socket set screw M6x12", name_ko: "세트 스크루 M6×12", part_class: "other", units: "mm", material: "S45C",
    drawing: { number: "VR-RB-015", scale: "5:1", projection: "third" },
    segments: [{ type: "thread", length: 12, diameter: 6, spec: "M6", pitch: 1 }],
    transitions: [{ at: 0, type: "chamfer", size: 0.5 }, { at: 1, type: "chamfer", size: 1 }],
    grooves: [], bore: null,
    features: [{ type: "hex_socket", end: "left", across_flats: 3, depth: 3 }],
    meta: { source: "golden", difficulty: 2 },
  },
  {
    dsl: "vringon-shaft/1.0", id: "countersunk-m6", name: "Countersunk socket screw M6x20", name_ko: "접시머리 나사 M6×20", part_class: "other", units: "mm", material: "SUS304",
    drawing: { number: "VR-RB-016", scale: "5:1", projection: "third" },
    segments: [{ type: "taper", length: 3.3, d_start: 12, d_end: 6, label: "접시 머리 90°" }, { type: "thread", length: 20, diameter: 6, spec: "M6", pitch: 1 }],
    transitions: [{ at: 2, type: "chamfer", size: 1 }],
    grooves: [], bore: null,
    features: [{ type: "hex_socket", end: "left", across_flats: 4, depth: 2 }],
    meta: { source: "golden", difficulty: 3 },
  },
  {
    dsl: "vringon-shaft/1.0", id: "stud-m12", name: "Double-end stud M12x60", name_ko: "스터드 볼트 M12×60", part_class: "other", units: "mm", material: "SCM435",
    drawing: { number: "VR-RB-017", scale: "1:1", projection: "third" },
    segments: [{ type: "thread", length: 15, diameter: 12, spec: "M12", pitch: 1.75, label: "식입측" }, { type: "cyl", length: 23, diameter: 12 }, { type: "thread", length: 22, diameter: 12, spec: "M12", pitch: 1.75, label: "너트측" }],
    transitions: [{ at: 0, type: "chamfer", size: 1.5 }, { at: 3, type: "chamfer", size: 1.5 }],
    grooves: [], bore: null, features: [],
    meta: { source: "golden", difficulty: 2 },
  },
];
